name: Setup CI Environment

inputs:
  key:
    required: true
    type: string
  cache_paths:
    required: true
    type: string
  enable_cache:
    required: false
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
  - name: Date
    id: date
    shell: bash
    # Cache action only accepts up to 10 keys.
    run: |
      set -e
      seq 0 1 9 | xargs -rI{} expr '(' "$(date -u '+%s')" '/' 3600 '/' 8 - {} ')' '*' 3600 '*' 8 | xargs -rI{} date -d @{} -u '+%FT%H' | nl -s ' ' -v0 | xargs printf 'date-%d=%s\n' >> "$GITHUB_OUTPUT"
      echo 'CRIS_CACHE_PATHS<<EOF' >> "$GITHUB_ENV"
      printf "%s" "${{ inputs.cache_paths }}" >> "$GITHUB_ENV"
      echo 'EOF' >> "$GITHUB_ENV"
  - uses: actions/cache@v4
  # PR should not save to shared cache.
    if: ${{ always() && inputs.enable_cache == 'true' && github.event_name != 'pull_request' && ! cancelled() }}
    with:
      key: ${{ inputs.key }}:${{ steps.date.outputs.date-0 }}
      path: ${{ env.CRIS_CACHE_PATHS }}
      restore-keys: |
        ${{ inputs.key }}:${{ steps.date.outputs.date-1 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-2 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-3 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-4 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-5 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-6 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-7 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-8 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-9 }}
  - uses: actions/cache/restore@v4
    if: ${{ always() && inputs.enable_cache == 'true' && github.event_name == 'pull_request' && ! cancelled() }}
    with:
      path: ${{ env.CRIS_CACHE_PATHS }}
      key: ${{ inputs.key }}:${{ steps.date.outputs.date-0 }}
      restore-keys: |
        ${{ inputs.key }}:${{ steps.date.outputs.date-1 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-2 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-3 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-4 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-5 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-6 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-7 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-8 }}
        ${{ inputs.key }}:${{ steps.date.outputs.date-9 }}
  - name: Config
    shell: bash
    run: |
      set -xe
      export HOME=/root
      ccache -M 1GiB -o compression=true -o compression_level=5
      ccache -svx
      ccache --show-config
      git config --global --add safe.directory "$(pwd)"
      mkdir -p ~/{.cache/{bazel,ccache,pip},.ccache}
  - name: Auth
    shell: bash
    run: |
      # Overwrite custom home dir set by GitHub Action because SSH does not respect that.
      export HOME=/root
      scripts/auth_github_ssh.sh
  - name: Fetch submodules
    shell: bash
    run: |
      export HOME=/root
      GIT_SSH_COMMAND='ssh -vvv' git submodule update --init --jobs 10 --recursive
