name: Setup CI Environment for Linter

inputs:
  key:
    required: true
    type: string
  enable_cache:
    required: false
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
  - uses: ./.github/actions/ci-env-setup
    with:
      key: ${{ inputs.key }}
      cache_paths: |
        /root/.cache/bazel
      enable_cache: ${{ inputs.enable_cache }}
