name: Clean up CI Environment

runs:
  using: "composite"
  steps:
  - name: Verify cleanness
    shell: bash
    run: |
      set -e
      export HOME=/root
      git --no-pager diff --exit-code --name-only
  - name: Summary
    shell: bash
    run: |
      set -e
      export HOME=/root
      ccache -X5
      ccache -svx
  - name: Prune cache
    shell: bash
    run: |
      set -e
      export HOME=/root
      ccache -M 512MiB
      ccache -X5
      ccache -svx
