name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build:20210926
    steps:
    - uses: actions/checkout@v2
    - name: Run linter
      run: make lint
    - name: Check diff
      run: git --no-pager diff --exit-code

  bazel:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build:20210926
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          /root/.cache/bazel
          /root/.cache/pip
          /root/.ccache
        key: ghcr.io/cyfitech/cris-build:20210926
    - name: Build
      run: export HOME=/root && scripts/build_all.sh -s
    - name: Test
      run: export HOME=/root && scripts/test_all.sh --nocache_test_results --test_output=errors -s
