name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-ubuntu2004:20221216
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-lint-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Config
      run: export HOME=/root && git config --global --add safe.directory "$(pwd)"
    - name: Check gitignore
      run: |
        set -ex
        export HOME=/root
        ! git --no-pager ls-files -z                            \
        | git --no-pager check-ignore --no-index --stdin -vz    \
        | tr '\0' '\n'                                          \
        | paste -d: - -                                         \
        | paste -d"$(printf '\v')" - -                          \
        | grep -v "$(printf '\v!')"                             \
        | tr '\v' '\t'                                          \
        | grep .
    - name: Run linter
      run: export HOME=/root && make -j lint tidy
    - name: Check diff
      run: export HOME=/root && git --no-pager diff --exit-code

  llvm11-debian11:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-debian11:20221216
    env:
      CC: clang-11
      CXX: clang++-11
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-build-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Build and Test
      run: export HOME=/root && scripts/bazel_wrapper.sh test --config=rel --config=prof --nocache_test_results --test_output=all -s //...
    - uses: ./.github/actions/ci-env-cleanup

  llvm12-ubuntu2004:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-ubuntu2004:20221216
    env:
      CC: clang-12
      CXX: clang++-12
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-build-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Build and Test
      run: export HOME=/root && scripts/bazel_wrapper.sh test --config=rel --config=prof --nocache_test_results --test_output=all -s //...
    - uses: ./.github/actions/ci-env-cleanup

  llvm13-debian11:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-debian11:20221216
    env:
      CC: clang-13
      CXX: clang++-13
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-build-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Build and Test
      run: export HOME=/root && scripts/bazel_wrapper.sh test --config=rel --config=prof --nocache_test_results --test_output=all -s //...
    - uses: ./.github/actions/ci-env-cleanup

  llvm14-ubuntu2204:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-ubuntu2204:20221216
    env:
      CC: clang-14
      CXX: clang++-14
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-build-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Build and Test
      run: export HOME=/root && scripts/bazel_wrapper.sh test --config=rel --config=prof --nocache_test_results --test_output=all -s //...
    - uses: ./.github/actions/ci-env-cleanup

  gcc10-debian11:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-debian11:20221216
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-build-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Build and Test
      run: export HOME=/root && scripts/bazel_wrapper.sh test --config=rel --config=prof --nocache_test_results --test_output=all -s //...
    - uses: ./.github/actions/ci-env-cleanup

  gcc10-ubuntu2004:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-ubuntu2004:20221216
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-build-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Build and Test
      run: export HOME=/root && scripts/bazel_wrapper.sh test --config=rel --config=prof --nocache_test_results --test_output=all -s //...
    - uses: ./.github/actions/ci-env-cleanup

  gcc11-ubuntu2204:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-ubuntu2204:20221216
    env:
      # Cannot use gcc-12 because of https://github.com/protocolbuffers/protobuf/issues/9948 (requires protobuf v3.21.0 or gcc 12.2)
      # https://github.com/protocolbuffers/protobuf/pull/10118 is needed for upgrading protobuf
      CC: gcc-11
      CXX: g++-11
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-build-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Build and Test
      run: export HOME=/root && scripts/bazel_wrapper.sh test --config=rel --config=prof --nocache_test_results --test_output=all -s //...
    - uses: ./.github/actions/ci-env-cleanup

  asan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-debian11:20221216
    env:
      CC: clang-13
      CXX: clang++-13
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-build-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Build and Test
      run: export HOME=/root && scripts/bazel_wrapper.sh test --config=asan --config=prof --nocache_test_results --test_output=all -s //...
    - uses: ./.github/actions/ci-env-cleanup

  ubsan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-debian11:20221216
    env:
      CC: clang-13
      CXX: clang++-13
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-build-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Build and Test
      run: export HOME=/root && scripts/bazel_wrapper.sh test --config=ubsan --config=prof --nocache_test_results --test_output=all -s //...
    - uses: ./.github/actions/ci-env-cleanup

  tsan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-debian11:20221216
    env:
      CC: clang-13
      CXX: clang++-13
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-build-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Build and Test
      run: export HOME=/root && scripts/bazel_wrapper.sh test --config=tsan --config=prof --nocache_test_results --test_output=all -s //...
    - uses: ./.github/actions/ci-env-cleanup

  make-llvm:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-debian11:20221216
    env:
      CC: clang-13
      CXX: clang++-13
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-build-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Build
      run: export HOME=/root && make build
    - uses: ./.github/actions/ci-env-cleanup

  make-gcc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyfitech/cris-build-debian11:20221216
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-build-env-setup
      with:
        key: ${{ github.job }}
        cris_base_ssh_token : ${{ secrets.CRIS_BASE_CI_SSH_PRIVKEY_ED25519 }}
        cris_xchg_ssh_token : ${{ secrets.CRIS_XCHG_CI_SSH_PRIVKEY_ED25519 }}
    - name: Build
      run: export HOME=/root && make build
    - uses: ./.github/actions/ci-env-cleanup
